// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using InternetServiceBack.Models.General;
//
//    var tokenSessionModel = TokenSessionModel.FromJson(jsonString);

namespace InternetServiceBack.Dtos.Common
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class TokenSessionDto
    {
        [JsonProperty("userId")]
        public Guid UserId { get; set; }

        [JsonProperty("dateExpired")]
        public string DateExpired { get; set; }
    }

    public partial class TokenSessionDto
    {
        public static TokenSessionDto FromJson(string json) => JsonConvert.DeserializeObject<TokenSessionDto>(json, InternetServiceBack.Dtos.Common.TokenSessionModelConverter.Settings);
    }

    public static class TokenSessionModelSerialize
    {
        public static string ToJson(this TokenSessionDto self) => JsonConvert.SerializeObject(self, InternetServiceBack.Dtos.Common.TokenSessionModelConverter.Settings);
    }

    internal static class TokenSessionModelConverter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}